### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by oscargong** [nriley/LBOfficeMRU#1]
Here is the log from console, hope it helps.
```
default	18:41:45.625996 +0800	LaunchBar	Recent Word Documents (net.sabi.LaunchBar.action.RecentWordDocuments): Script Error: </usr/bin/env python /Users/Oscar/Library/Application Support/LaunchBar/Actions/Recent Word Documents.lbaction/Contents/Scripts/default.py>
Traceback (most recent call last):
  File "/Users/Oscar/Library/Application Support/LaunchBar/Actions/Recent Word Documents.lbaction/Contents/Scripts/default.py", line 14, in <module>
    items += mruservice.items_for_app(APP_NAME, APP_BUNDLE_ID, APP_URL_PREFIX, EXTENSION_TO_ICON_NAME)
  File "/var/folders/q_/w1m4zdp56ps5_hqj8lq7vkl40000gn/T/upload_LBOfficeMRU1DTfwo/LBOfficeMRU 1.0b2/Recent Word Documents.lbaction/Contents/Scripts/mruservice.py", line 51, in items_for_app
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u9879'
```
```
default	18:41:45.626225 +0800	LaunchBar	Recent Word Documents (net.sabi.LaunchBar.action.RecentWordDocuments): Script exited with status: 1
```

Recent Excel Documents and Recent PowerPoint Documents return similar logs.

**Comment by nriley** [comment]
Sorry for the delay — I have no idea how I missed this when you filed it!

It looks like the issue is when you save a document on OneDrive with characters such as 项 in it.  I just need to encode it in UTF-8 and it is fine.

@OscarGong, give this a shot and let me know if it works:
[LBOfficeMRU-1.0b3.zip](https://github.com/nriley/LBOfficeMRU/files/880827/LBOfficeMRU-1.0b3.zip)

**Comment by oscargong** [comment]
Thanks @nriley ! It now works fine.
